version: '3'
volumes:
  data:
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    command: bash "run_django.sh"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "9432:5432"
