# Generated by Django 4.1 on 2022-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=50)),
                ("client_org", models.CharField(max_length=100)),
                ("number", models.PositiveIntegerField(help_text="Number of the bill")),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the service",
                        max_digits=12,
                    ),
                ),
                ("date", models.DateField(help_text="Date when service has occurred")),
                (
                    "service",
                    models.CharField(help_text="Service description", max_length=100),
                ),
            ],
            options={
                "ordering": ("client_name",),
            },
        ),
    ]
