# Generated by Django 4.1 on 2022-08-11 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("консультация", "Консультация"),
                            ("лечение", "Лечение"),
                            ("стационар", "Стационар"),
                            ("диагностика", "Диагностика"),
                            ("лаборатория", "Лаборатория"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        help_text="Unique code for service class",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
    ]
