# Generated by Django 4.1 on 2022-08-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_serviceclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinquiry",
            name="service_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bill_inquiries",
                to="bills.serviceclass",
            ),
        ),
    ]
